# Generated by Django 5.1rc1 on 2024-08-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curo',
            new_name='Curso',
        ),
    ]
